### ISSUE TITLE
shape languages and validation features

### ISSUE THREAD

**Issue by phtyson** [w3c/sparql-service-description#26]
Is it within scope of the WG to add shape language feature instances and description of validation endpoints? Would also affect sparql-protocol document.

**Comment by rubensworks** [comment]
I suspect this won't be in-scope for this WG.
This might be a better place to add this suggestion: https://github.com/w3c/sparql-dev

**Comment by pfps** [comment]
I view this as out of scope.

**Comment by pchampin** [comment]
This was discussed during the [rdf-star meeting on 26 September 2024](https://www.w3.org/2024/09/26-rdf-star-minutes.html#t01).

**Comment by pchampin** [comment]
This was discussed during the [rdf-star meeting on 26 September 2024](https://www.w3.org/2024/09/26-rdf-star-minutes.html#t03).

**Comment by pchampin** [comment]
This was discussed during the [rdf-star meeting on 26 September 2024](https://www.w3.org/2024/09/26-rdf-star-minutes.html#t01).

<details><summary><i>View the transcript</i></summary>

<h3>Un-star operation to support RDF Dataset Canonicalization? <a href="https://github.com/w3c/rdf-star-wg/issues/114" rel="noopener noreferrer">1</a></h3>
<p><cite>niklasl:</cite> I tried to summarize the two options on the table: unstar based on named graphs, or base on classical reification</p>
<p><cite>&lt;william_vw&gt;</cite> present_</p>
<p><cite>niklasl:</cite> also the question whether it is targetting canonicalization alone, or more general<br>
<span>… if c14n was defined on RDF 1.2 with triple terms, unstar would not be necessary.</span></p>
<p><cite>pfps:</cite> as far as I'm concerned, this group does not need to do anything about c14n.<br>
<span>… We could be nice, but not spend to much effort about this.</span><br>
<span>… We could say "RDF-CANON should be extended to RDF 1.2. In the mean time, use an unstar mapping that essentially uses reification."</span></p>
<p><cite>&lt;pfps&gt;</cite> This should be specified a bit more precisely.</p>
<p><cite>tl:</cite> I agree that we should provide a reification-based unstar mapping, that does not require named graphs.<br>
<span>… Several variants are described in the github issue, I think the reification-based is the less controversial.</span></p>
<p><cite>niklasl:</cite> we need to know what the type of triple terms is.</p>
<p><cite>gkellogg_:</cite> although the unstar is necessary for c14n, there are probably other cases that require it.<br>
<span>… I think round-tripping is important.</span><br>
<span>… We must consider SPARQL as well, being able to run it on an RDF 1.1 database.</span></p>
<p><cite>&lt;niklasl&gt;</cite> +1 to "unstar a query" too (to put annotation in existing graph stores and use it in production)</p>
<p><cite>gkellogg_:</cite> It would also be interesting to be able to turn standard reification into triple terms.</p>
<p><cite>&lt;niklasl&gt;</cite> (noting that I have no problem "unstarring queries" manually)</p>
<p><cite>ora:</cite> could be an issue if there is a mix of old-style and new-style.</p>
<p>gkellogg_; we need to decide if that's a problem.</p>
<p><cite>&lt;niklasl&gt;</cite> +1 to that to (is the target 1.2 basic or 1.1)</p>
<p><cite>&lt;pfps&gt;</cite> In my opinion an unstar mapping is only to be used as an interim solution.  It does not have to support round-tripping.  It does not need to preserve non-isomorphism for RDF graphs that are not "good" RDF 1.2 graphs (misusing rdf:reifies, misusing triple terms, not well-formed if we still have this).</p>
<p><cite>AndyS:</cite> we need to decide if we are turning RDF 1.2 Full into RDF 1.2 Classic or into RDF 1.1. RDF 1.2 has text direction, RDF 1.1 does not. The algorithm would not be the same.</p>
<p><cite>gkellogg_:</cite> I claim that base direction would not impact c14n.<br>
<span>… In the sense that it can easily be integrated in the existing algorithm.</span></p>
<p><cite>pfps:</cite> given that there is more than c14n does not handle, I say we don't do anything.</p>
<p><cite>ora:</cite> who's gonna get hurt if we don't do anything?</p>
<p><cite>gkellogg_:</cite> the c14n algorithm is not so complicated, but the proof that it's correct are.<br>
<span>… It is not likely that a new group is going to be chartered to do a new algorithm.</span><br>
<span>… If we don't provide an unstar mapping, the RCH group would probably provide one.</span><br>
<span>… We do have the Full and Basic profiles.</span></p>
<p><cite>pchampin:</cite> I simpathise with pfps position, but agree that if we don't do it someone else will.<br>
<span>… I believe there are other use cases for un-star.</span><br>
<span>… This provides a useful way to go between profiles.</span></p>
<p><cite>&lt;tl&gt;</cite> I think we should do it (backwards compatibility, and illustrate the meaning of triple terms), and re @AndyS its target should be RDF 1.1</p>
<p><cite>AndyS:</cite> I think we should do something, especially since the CG report already mentions an unstar mapping.</p>
<p><cite>&lt;niklasl&gt;</cite> This issue has mutated a bit, and should perhaps be retitled again, to e.g. "Define an unstarred form into RDF 1.1(?)" (to cater for everything specified and/or deployed, including C14N and reasoners, that will not upgrade to RDF 1.2 overnight)?</p>
<p><cite>AndyS:</cite> does not have to be a big thing, can be non-normative.</p>
<p><cite>ora:</cite> if there are other use-cases for this than c14n, we run the risk that other people do it differently.<br>
<span>… We are in the best position to do it.</span><br>
<span>… What are our use-cases? Is it someone who wants to use RDF 1.2 with their RDF 1.1 implementation?</span></p>
<p><cite>&lt;Zakim&gt;</cite> pfps, you wanted to point out that <a href="https://www.w3.org/TR/rdf-canon/" rel="noopener noreferrer">https://<wbr>www.w3.org/<wbr>TR/<wbr>rdf-canon/</a> has flas</p>
<p><cite>ora:</cite> Other question is round-tripping.</p>
<p><cite>pfps:</cite> the RDF-CANON has a big problem, it is unclear about what its input is.<br>
<span>… The input is an n-quads documents, but in other places it talks about the input dataset.</span><br>
<span>… I don't want us to get involved in this.</span><br>
<span>… It is not up to us to fix that problem.</span></p>
<p><cite>gkellogg_:</cite> you seem to be asserting that it is a flawed recommendation.</p>
<p><cite>&lt;pfps&gt;</cite> From RDF canonicalization "This document outlines an algorithm for generating a canonical serialization of an RDF dataset given an RDF dataset as input."</p>
<p><cite>gkellogg_:</cite> It uses n-quads as an input to leverage the blank node labels.</p>
<p><cite>&lt;pfps&gt;</cite> From the docuemnt "input dataset</p>
<p><cite>&lt;pfps&gt;</cite>     The abstract RDF dataset that is provided as input to the algorithm."</p>
<p><cite>gkellogg_:</cite> It was reviewed and I think it is an adequate recommdnation.</p>
<p><cite>&lt;pchampin&gt;</cite> s/recommndnation/recommendation</p>
<p><cite>&lt;pfps&gt;</cite> The algorithm, however, starts with an N-quads document.</p>
<p><cite>niklasl:</cite> I think the argument about migrating from RDF 1.1 is a good one.</p>
<p><cite>&lt;tl&gt;</cite> +1 to niklasl</p>
<p><cite>pchampin:</cite> I think we should use RDF 1.2 Classic as the baseline, not RDF 1.1.</p>
<p><cite>niklasl:</cite> I sympathise with this position.</p>
<p><cite>&lt;william_vw&gt;</cite> I assume RDF 1.2 classic means without triple terms?</p>
<p><cite>niklasl:</cite> There are ways in JSON-LD 1.1 to encode base direction in RDF 1.1, but there are two options, none of them ideal.</p>
<p><cite>ora:</cite> what would it require to deal with base direction in RDF 1.1?</p>
<p><cite>&lt;tl&gt;</cite> @william_vw yes</p>
<p><cite>&lt;william_vw&gt;</cite> @tl thanks</p>
<p><cite>gkellogg_:</cite> we would probably go with one of the JSON-LD options, probably the i18n datatype.</p>
<p><cite>&lt;niklasl&gt;</cite> I'd agree on i18n datatype version of lang-literals-with-dir.</p>
<p><cite>ora:</cite> I don't like the idea to deem this somebody else's problem<br>
<span>… Depends how much work we want to put into it, pieces of solution already exist.</span></p>
<p><cite>pchampin:</cite> I agree that we need to do something. But, let's be clear on what we're trying to solve.<br>
<span>… I'm worried about using RDF 1.1 as a baseline.</span><br>
<span>… It's also useful for the "inter-profile" operation.</span><br>
<span>… If we agree that this is the scope, I can take it into account in my PR.</span></p>
<p><cite>ora:</cite> it would solve the c14n "for free". Ultimately RDF-CANON has to be adapted to RDF 1.2, but we know it may take time.</p>
<p><cite>&lt;ora&gt;</cite> STRAWPOLL: Should we include an un-star algorithm in the 1.2 spec? (some questions remain...)</p>
<p><cite>&lt;pfps&gt;</cite> -1</p>
<p><cite>&lt;niklasl&gt;</cite> +1</p>
<p><cite>&lt;gkellogg_&gt;</cite> +1</p>
<p><cite>&lt;tl&gt;</cite> +1</p>
<p><cite>&lt;ora&gt;</cite> +1</p>
<p><cite>&lt;william_vw&gt;</cite> +1</p>
<p><cite>&lt;MacTed&gt;</cite> +1</p>
<p><cite>&lt;olaf&gt;</cite> +1</p>
<p><cite>&lt;pchampin&gt;</cite> +1</p>
<p><cite>&lt;AndyS&gt;</cite> +1</p>
<p><cite>&lt;Dominik_T&gt;</cite> -0.5</p>
<p><cite>gtw:</cite> what would normative mean? not all implementations need the unstar mapping?</p>
<p><cite>pchampin:</cite> it needs to be normative if other specs want to normatively refer to it.</p>
<p><cite>gkellogg_:</cite> implementations can be compliant without passing all the tests</p>
<p><cite>&lt;gtw&gt;</cite> +1</p>
<p><cite>gtw:</cite> the manifest vocabulary allows us to flag tests as requiring certain features</p>
<p><cite>tl:</cite> it seems like a straightforward implementation, not putting unreasonable burden on implementations, so let's make it normative</p>
<p><cite>&lt;niklasl&gt;</cite> I like this direction (not requiring 1.2 implementations to have an unstar operation plus adding a new set of tests for this feature (usable to opt-in for those who support it)).</p>
<p><cite>ora:</cite> if we didn't make it normative, that would nudge the RCH group to do the work properly</p>
<p><cite>AndyS:</cite> the more tests we put, the more work that is, and the less likely it is that implementations migrate</p>
<p><cite>ora:</cite> I don't know the answer to this normative/non-normative thing. If we make a non-normative section, then people will hopefully not make their own.<br>
<span>… If some days the RCH group makes a 1.2, this is an interim solution.</span></p>
<p><cite>pchampin:</cite> in the interest of time, I suggest we defer the nonrmative/non-normative question until we have a PR to discuss on</p>
<p><cite>&lt;gb&gt;</cite> <strong><a href="https://github.com/w3c/rdf-star-wg/issues/114" rel="noopener noreferrer">Issue 114</a></strong> Un-star operation to support RDF Dataset Canonicalization? (by niklasl) [needs discussion] [discuss-f2f]</p>
<p><cite>&lt;gb&gt;</cite> <strong><a href="https://github.com/w3c/sparql-service-description/issues/26" rel="noopener noreferrer">Issue 26</a></strong> shape languages and validation features (by phtyson) [discuss-f2f] [needs discussion]</p>
<p><cite>&lt;gb&gt;</cite> <strong><a href="https://github.com/w3c/rdf-star-wg/issues/127" rel="noopener noreferrer">Issue 127</a></strong> Material about `rdf:ReificationProperty` (by afs) [needs discussion] [discuss-f2f]</p>
<p><cite>&lt;gb&gt;</cite> <strong><a href="https://github.com/w3c/sparql-query/issues/156" rel="noopener noreferrer">Issue 156</a></strong> Addressing SPARQL EXISTS errata (by afs) [discuss-f2f] [needs discussion]</p>
<p><cite>&lt;niklasl&gt;</cite> I see no big risk in just making it informative. (Famous last words; but... In practice, for "reasons", lots of implementations aren't 1:1 with what's normative.)</p>
<p><cite>&lt;gb&gt;</cite> <strong><a href="https://github.com/w3c/rdf-semantics/issues/49" rel="noopener noreferrer">Issue 49</a></strong> Define an interpretation of Triple Terms (by niklasl) [discuss-f2f] [needs discussion]</p>
<p><cite>&lt;niklasl&gt;</cite> I see no *big* risk in just making it informative. (Famous last words; but... In practice, for "reasons", lots of implementations aren't 1:1 with what's normative.)</p>

<hr /></details>

**Comment by pchampin** [comment]
This was discussed during the [rdf-star meeting on 26 September 2024](https://www.w3.org/2024/09/26-rdf-star-minutes.html#t03).

<details><summary><i>View the transcript</i></summary>

<h3>Shape languages and validation features <a href="https://github.com/w3c/sparql-service-description/issues/26" rel="noopener noreferrer">2</a></h3>
<p><cite>&lt;ora&gt;</cite> PROPOSAL: Mark as out-of-scope and close</p>
<p><cite>&lt;gkellogg_&gt;</cite> +1</p>
<p><cite>&lt;pchampin&gt;</cite> +1</p>
<p><cite>&lt;tl&gt;</cite> +1</p>
<p><cite>&lt;ora&gt;</cite> +1</p>
<p><cite>&lt;gtw&gt;</cite> +1</p>
<p><cite>&lt;doerthe&gt;</cite> +1</p>
<p><cite>&lt;niklasl&gt;</cite> +1</p>
<p><cite>&lt;TallTed&gt;</cite> +1</p>
<p><cite>&lt;eBremer&gt;</cite> +1</p>
<p><cite>&lt;Dominik_T&gt;</cite> +0.5</p>
<p><cite>&lt;AndyS&gt;</cite> +1</p>
<p><strong>RESOLUTION:</strong> Mark as out-of-scope and close</p>

<hr /></details>
